facebook:
  client:
    clientId: 545130232539780
    clientSecret: 056a57571645327b0f4fcf3162e9c9cc
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=name,birthday,gender,email